import sequelize from '../config/database.js';
import Product from './Product.js';
import { Op } from 'sequelize';
import Department from './Department.js';
import Employee   from './Employee.js';
import User    from './User.js';
import Profile from './Profile.js';
import Student   from './Student.js';
import Course    from './Course.js';
import Enrolment from './Enrolment.js';


console.log(Product.tableName);
try {
  await sequelize.authenticate();            // authenticate() — tests the connection
  console.log('Database connected successfully!');
} catch (err) {
  console.error('Connection failed:', err);
}

// sync() compares the model definition with the real table.
// { force: true } drops and re-creates the table on every run (dev only!).
await sequelize.sync({ force: true });
console.log('Tables synced!');
const p1 = await Product.create({
  name: 'Laptop',
  price: 1299.99,
  stock: 10,
});
const p2 = await Product.create({ 
    name: 'Mouse', 
    price: 49.99, 
    stock: 50 
});
console.log('Created:', p1.name, p2.name);
const allProducts = await Product.findAll();
console.log('All products:', allProducts.map(p => p.name));

// findByPk(id) — look up the row whose PRIMARY KEY = id
const found = await Product.findByPk(1);     // id = 1
if (found) {
  console.log('Found:', found.name);     // .name
} else {
  console.log('Not found');
}



// Products cheaper than $100
const cheap = await Product.findAll({
  where: {
    price: { [Op.lt]: 100 },   // Op.lt = less than
  },
});
console.log('Cheap products:', cheap.length);


// Option A: fetch the instance first, then save changes
const product = await Product.findByPk(1);
product.price = 999.99;             // change the price field
await product.save();              // .save() persists the change

console.log('Updated price:', product.price);


// Option B: Product.update(values, { where })
const [affectedRows] = await Product.update(
  { stock: 0 },                      // set stock = 0
  { where: { price: { [Op.gt]: 500 } } }   // for products over $500
);
console.log('Rows updated:', affectedRows);


// Instance destroy
const toDelete = await Product.findByPk(2);
await toDelete.destroy();             // .destroy()
console.log('Deleted product with id 2');

// Static destroy (delete all out-of-stock)
await Product.destroy({ where: { stock: 0 } });
console.log('Cleared out-of-stock products');


// One department has MANY employees
Department.hasMany( Employee );        // .hasMany()

// Each employee BELONGS TO one department
Employee.belongsTo( Department );        // .belongsTo()

await sequelize.sync({ force: true });

const engineering = await Department.create({ name: 'Engineering' });
// .createEmployee() is generated by hasMany — it sets the FK automatically
await engineering.createEmployee({ name: 'Alice', jobTitle: 'Backend Dev' });
await engineering.createEmployee({ name: 'Bob',   jobTitle: 'Frontend Dev' });

const dept = await Department.findByPk(1, {
  include: [ Employee ],   // pass the Employee model to include its rows
});
console.log('Employees:', dept.Employees.map(e => e.name));


// A User HAS ONE Profile — the FK (UserId) lives on the Profile table
User.hasOne( Profile );               // .hasOne()

// A Profile BELONGS TO a User
Profile.belongsTo( User );               // .belongsTo()

await sequelize.sync({ force: true });

const user = await User.create({ username: 'sokha', email: 'sokha@example.com' });
// .createProfile() is generated by hasOne
await user.createProfile({ bio: 'Backend developer', avatar: 'sokha.png' });
console.log('User created with profile.');

const fullUser = await User.findByPk(1, {
  include: [ Profile ],   // include the Profile model
});
console.log(fullUser.username, '-', fullUser.Profile.bio);



// Student belongs to many Courses (through the Enrolment junction table)
Student.belongsToMany( Course, { through: Enrolment });    // .belongsToMany(), Enrolment

// Course belongs to many Students (the reverse side)
Course.belongsToMany( Student, { through: Enrolment }); // .belongsToMany()

await sequelize.sync({ force: true });
console.log('Many-to-Many schema ready.');


const alice   = await Student.create({ name: 'Alice',   email: 'alice@school.com' });
const bob     = await Student.create({ name: 'Bob',     email: 'bob@school.com' });

const math    = await Course.create({ title: 'Mathematics', credits: 4 });
const cs      = await Course.create({ title: 'Computer Science', credits: 3 });

// .addCourse() is generated by belongsToMany — it inserts a row in Enrolment
await alice.addCourse( math, { through: { grade: 'A' } });   // addCourse()
await alice.addCourse( cs,   { through: { grade: 'B+' } });
await bob.addCourse( math, { through: { grade: 'C' } });     // addCourse()

const aliceCourses = await alice.getCourses();     // .getCourses()
console.log('Alice is enrolled in:');
aliceCourses.forEach(c => console.log(' -', c.title, '| grade:', c.Enrolment.grade));


const mathStudents = await math.getStudents();      // .getStudents()
console.log('Math students:', mathStudents.map(s => s.name));

const allStudents = await Student.findAll({
  include: [{
    model: Course,           // Course model
    through: {
      attributes: ['grade'] // only include the 'grade' column from Enrolment
    }
  }]
});

allStudents.forEach(s => {
  console.log(`${s.name}:`);
  s.Courses.forEach(c =>
    console.log(`  ${c.title} — grade: ${c.Enrolment.grade}`)   // .grade
  );
});


